// Generates the prod-shipped font subsets:
//
//   - src/assets/fonts/devicon-subset.woff2
//       Devicon font subsetted to the 18 glyphs SkillsCarousel + Projects use.
//       Drops devicon's full font (~480 KB woff) down to ~5 KB woff2.
//
//   - src/assets/fonts/CentraNo2-{Book,Medium,Bold}.woff2
//       Centra TTFs converted to woff2 with no subsetting (full character set
//       preserved — body copy + headings can use any glyph). Drops ~243 KB
//       TTFs to ~140 KB woff2.
//
// Run: node scripts/build-fonts.mjs
// Should be re-run after upgrading devicon (codepoints can shift between
// versions — devicon 2.17 famously reshuffled them, hence the 2.15 pin).

import subsetFont from 'subset-font';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

// Devicon classes actually used in src/. If you add a new skill icon to
// SkillsCarousel.tsx, add the class here and re-run this script.
const DEVICON_USED = [
    'bash-plain',
    'html5-plain',
    'css3-plain',
    'javascript-plain',
    'typescript-plain',
    'jquery-plain',
    'react-original',
    'angularjs-plain',
    'nodejs-plain',
    'mongodb-plain',
    'php-plain',
    'ruby-plain',
    'rails-plain',
    'postgresql-plain',
    'amazonwebservices-original',
    'linux-plain',
    'github-original',
    'git-plain'
];

const fmt = (b) => `${(b / 1024).toFixed(1)} KB`;

async function buildDeviconSubset() {
    const cssPath = path.join(root, 'node_modules/devicon/devicon.min.css');
    const fontPath = path.join(root, 'node_modules/devicon/fonts/devicon.ttf');
    const outFontPath = path.join(root, 'src/assets/fonts/devicon-subset.woff2');
    const outCssPath = path.join(root, 'src/assets/fonts/devicon-subset.css');

    const css = await fs.readFile(cssPath, 'utf8');
    const chars = [];
    const rules = [];
    for (const cls of DEVICON_USED) {
        const ruleRe = new RegExp(
            `([^}]*\\.devicon-${cls}:before[^}]*)\\{content:"([^"]+)"\\}`
        );
        const m = css.match(ruleRe);
        if (!m) throw new Error(`devicon class not found in CSS: ${cls}`);
        chars.push(m[2]);
        // Use the single class form rather than the original compound selector
        // — keeps the generated CSS minimal and obvious.
        rules.push(
            `.devicon-${cls}:before { content: "\\${m[2].codePointAt(0).toString(16)}"; }`
        );

        // The brand-color `.colored` rule lives next to the :before in
        // devicon's CSS but often inside a compound selector with the
        // matching `-wordmark` variant we don't ship. Match any rule whose
        // selector list includes `.devicon-<cls>.colored`, then re-emit it
        // as a single-class rule. Some classes legitimately have no
        // colored rule (the icon ships at its native color); skip those.
        const colorRe = new RegExp(
            `[^}]*\\.devicon-${cls}\\.colored[^}]*\\{color:(#[A-Fa-f0-9]+)\\}`
        );
        const c = css.match(colorRe);
        if (c) {
            rules.push(`.devicon-${cls}.colored { color: ${c[1]}; }`);
        }
    }

    const ttf = await fs.readFile(fontPath);
    const woff2 = await subsetFont(ttf, chars.join(''), { targetFormat: 'woff2' });
    await fs.writeFile(outFontPath, woff2);

    // Self-contained replacement for `@import "devicon"`: declares the
    // subset @font-face and only the 18 :before rules we ship.
    const cssOut = `/* GENERATED by scripts/build-fonts.mjs — do not edit by hand. */
@font-face {
    font-family: "devicon";
    src: url("./devicon-subset.woff2") format("woff2");
    font-weight: normal;
    font-style: normal;
    font-display: swap;
}

[class^="devicon-"], [class*=" devicon-"] {
    font-family: "devicon" !important;
    speak: never;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

${rules.join('\n')}
`;
    await fs.writeFile(outCssPath, cssOut);

    console.log(
        `devicon: ${DEVICON_USED.length} glyphs · ${fmt(ttf.length)} ttf → ${fmt(woff2.length)} woff2`
    );
}

async function buildCentraWoff2() {
    const fontDir = path.join(root, 'src/assets/fonts');
    const variants = ['Book', 'Medium', 'Bold'];
    for (const v of variants) {
        const ttfPath = path.join(fontDir, `CentraNo2-${v}.ttf`);
        const outPath = path.join(fontDir, `CentraNo2-${v}.woff2`);
        const ttf = await fs.readFile(ttfPath);
        // No subsetting — pass an empty string AND wildcard would be invalid;
        // pass the full ASCII + Latin-1 range. subset-font requires text or
        // unicode ranges. Use Latin-1 supplement + ASCII covers everything
        // the portfolio's English copy uses without keeping non-Latin glyphs.
        const text = Array.from({ length: 256 }, (_, i) => String.fromCodePoint(i)).join('');
        const woff2 = await subsetFont(ttf, text, { targetFormat: 'woff2' });
        await fs.writeFile(outPath, woff2);
        console.log(
            `Centra ${v.padEnd(6)}: ${fmt(ttf.length)} ttf → ${fmt(woff2.length)} woff2`
        );
    }
}

await buildDeviconSubset();
await buildCentraWoff2();
